#!/usr/bin/env bash

Namespace="prod"
Name="go-rpc-account"
RegistryServer="{{.registry.server}}"
RegistryUsername="{{.registry.username}}"
RegistryPassword="{{.registry.password}}"
MysqlServer="{{.mysql.server}}"
MysqlRootPassword="{{.mysql.rootPassword}}"
MysqlUsername="{{.mysql.username}}"
MysqlPassword="{{.mysql.password}}"
MysqlDatabase="account"
RedisAddr="{{.redis.addr}}"
RedisPassword="{{.redis.password}}"
EmailServer="{{.email.server}}"
EmailPassword="{{.email.password}}"
EmailFrom="{{.email.from}}"
EmailPort="{{.email.port}}"
PullSecrets="hatlonely-pull-secrets"
ImageRepository="hatlonely/go-rpc-account"
ImageTag="1.0.0"
ReplicaCount=2
IngressHost="k8s.account.hatlonely.com"
IngressSecret="k8s-secret"
K8sContext="homek8s"
